import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Imagine a world where everyone on the planet is free to do their{' '}
          <Link className={styles.emphasis} href="docs/philosophy">lives&apos; work.</Link>
        </h1>

        <p className={styles.description}>
          Get started by reading our philosophy above, or deep diving into our areas of work below.
        </p>

        <div className={styles.grid}>
          <a href="blockchain" className={styles.card}>
            <h2>Blockchain &rarr;</h2>
            <p>How decentralization of power will be the greatest catalyst for social change in our time.</p>
          </a>

          <a href="quantum" className={styles.card}>
            <h2>Quantum Computing &rarr;</h2>
            <p>How quantum computing will bring about a positive impact on the environment.</p>
          </a>

          <a href="bci" className={styles.card}>
            <h2>Brain Computer Interfaces &rarr;</h2>
            <p>How BCI will allow humanity to break down the limits of possible.</p>
          </a>

          <a href="agi" className={styles.card}>
            <h2>Artificial General Intelligence &rarr;</h2>
            <p>
              The final piece to the puzzle of solving all our problems.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Do you want to help build this future? Join us!
      </footer>
    </div>
  )
}
